### ISSUE TITLE
Will you submit this to the OpenWrt packages repository?

### ISSUE THREAD

**Issue by arinc9** [heiher/openwrt-hev-socks5-tproxy#1]
Hello! I am very happy to see a lightweight SOCKS5 server implementation, and a SOCKS5 client implementation to provide transparent proxying. I see that the server is already on the OpenWrt packages repository; will you submit this one there?

**Comment by heiher** [comment]
Okay. I'll do that.

**Comment by heiher** [comment]
https://github.com/openwrt/packages/pull/24791

**Comment by arinc9** [comment]
Great, thank you very much!
